name: 'Update Refs'
description: 'Update submodule commits based on trigger'
inputs:
  trigger:
    description: 'Which repo triggered the workflow'
    required: true
    default: ''
  ref:
    description: 'New ref/commit to checkout'
    required: true
    default: ''
  enable_summary:
    description: 'Enable Job Summary'
    required: true
    default: 'true'
outputs:
  num-changed:
    description: "Number of changes in repo"
    value: ${{ steps.count-files.outputs.NUM_CHANGED }}
  cdsl_ref:
    description: "Commit Ref"
    value: ${{ steps.refs.outputs.cdsl_ref }}
  s4e_cdsl_ref:
    description: "Commit Ref"
    value: ${{ steps.refs.outputs.s4e_cdsl_ref }}
  examples_ref:
    description: "Commit Ref"
    value: ${{ steps.refs.outputs.examples_ref }}
  s4e_examples_ref:
    description: "Commit Ref"
    value: ${{ steps.refs.outputs.s4e_examples_ref }}
  seal5_ref:
    description: "Commit Ref"
    value: ${{ steps.refs.outputs.seal5_ref }}
  etiss_ref:
    description: "Commit Ref"
    value: ${{ steps.refs.outputs.etiss_ref }}
  m2isar_ref:
    description: "Commit Ref"
    value: ${{ steps.refs.outputs.m2isar_ref }}

runs:
  using: "composite"
  steps:
    - name: Update CDSL ref
      if: inputs.trigger == 'cdsl'
      run:
        git -C etiss_arch_riscv checkout ${{ inputs.ref }}
        git -C etiss_arch_riscv submodule update --init --recursive
        git add etiss_arch_riscv
        echo "Updated Ref: etiss_arch_riscv -> ${{ inputs.ref }}" >> $GITHUB_STEP_SUMMARY

    - name: Update S4E CDSL ref
      if: inputs.trigger == 's4e-cdsl'
      run: |
        git -C riscv-coredsl-extensions checkout ${{ inputs.ref }}
        git add riscv-coredsl-extensions
        echo "Updated Ref: riscv-coredsl-extensions -> ${{ iyynputs.ref }}" >> $GITHUB_STEP_SUMMARY

    - name: Update M2-ISA-R ref
      if: inputs.trigger == 'm2isar'
      run: |
        git -C M2-ISA-R checkout ${{ inputs.ref }}
        git add M2-ISA-R
        echo "Updated Ref: M2-ISA-R -> ${{ inputs.ref }}" >> $GITHUB_STEP_SUMMARY

    - name: Update Seal5 ref
      if: inputs.trigger == 'seal5'
      run: |
        git -C seal5 checkout ${{ inputs.ref }}
        git -C seal5 submodule update --init --recursive
        git add seal5
        echo "Updated Ref: seal5 -> ${{ inputs.ref }}" >> $GITHUB_STEP_SUMMARY

    - name: Update Examples ref
      if: inputs.trigger == 'examples'
      run: |
        git -C etiss_riscv_examples checkout ${{ inputs.ref }}
        git -C etiss_riscv_examples submodule update --init --recursive
        git add etiss_riscv_examples

    - name: Update S4E Examples ref
      if: inputs.trigger == 's4e-examples'
      run: |
        git -C etiss_riscv_examples_s4e checkout ${{ inputs.ref }}
        git -C etiss_riscv_examples_s4e submodule update --init --recursive
        git add etiss_riscv_examples_s4e
        echo "Updated Ref: etiss_riscv_examples_s4e -> ${{ inputs.ref }}" >> $GITHUB_STEP_SUMMARY

    - name: Update ETISS ref
      if: inputs.trigger == 'etiss'
      run: |
        git -C etiss checkout ${{ inputs.ref }}
        git add etiss
        echo "Updated Ref: etiss -> ${{ inputs.ref }}" >> $GITHUB_STEP_SUMMARY
    # TODO: add to summary and outputs
    - name: Get Refs
      id: refs
      run: |
        echo "seal5_ref=$(git -C seal5 rev-parse HEAD)" >> $GITHUB_OUTPUT
        echo "etiss_ref=$(git -C etiss rev-parse HEAD)" >> $GITHUB_OUTPUT
        echo "examples_ref=$(git -C etiss_riscv_examples rev-parse HEAD)" >> $GITHUB_OUTPUT
        echo "s4e_examples_ref=$(git -C etiss_riscv_examples_s4e rev-parse HEAD)" >> $GITHUB_OUTPUT
        echo "m2isar_ref=$(git -C M2-ISA-R rev-parse HEAD)" >> $GITHUB_OUTPUT
        echo "cdsl_ref=$(git -C etiss_arch_riscv rev-parse HEAD)" >> $GITHUB_OUTPUT
        echo "s4e_cdsl_ref=$(git -C riscv-coredsl-extensions rev-parse HEAD)" >> $GITHUB_OUTPUT


    - name: Add and count changed files
      id: count-files
      working-directory: ./
      run: |
        NUM_STAGED=$(git diff --cached --numstat | wc -l 2>&1)
        echo "NUM_CHANGED=$NUM_STAGED" >> $GITHUB_OUTPUT
